- id: npm-groovy-lint
  name: Lint groovy files
  description: Groovy & Jenkinsfile Linter
  entry: docker.io/nvuillam/npm-groovy-lint --output txt --noserver
  language: docker_image
  types: [groovy]